export let lavaScs = [
    "Magma Slug",
    "Moogma",
    "Lava Leech",
    "Pyroclastic Worm",
    "Fire Eel",
    "Taurus",
    "Lava Flame",
    "Flaming Worm"
]

export let waterScs = [
    "Squid",
    "Sea Walker",
    "Night Squid",
    "Sea Guardian", 
    "Sea Witch", 
    "Sea Archer", 
    "Rider of the Deep",
    "Catfish",
    "Sea Leech",
    "Guardian Defender",
    "Deep Sea Protector",
    "Water Hydra",
    "Sea Emperor",
    "Oasis Rabbit", 
    "Oasis Sheep",
    "Scarecrow", 
    "Nightmare",
    "Werewolf",
    "Phantom Fisher",
    "Grim Reaper",
    "Frozen Steve",
    "snowman",
    "Grinch", 
    "Yeti",
    "Nutcracker",
    "Reindrake",
    "Nurse Shark",
    "Blue Shark",
    "Tiger Shark",
    "Great White Shark",
    "Agarimoo",
    "Poisoned Water Worm"
]
export let allScs = [
    "Squid",
    "Sea Walker",
    "Night Squid",
    "Sea Guardian", 
    "Sea Witch", 
    "Sea Archer", 
    "Rider of the Deep",
    "Catfish",
    "Sea Leech",
    "Guardian Defender",
    "Deep Sea Protector",
    "Water Hydra",
    "Sea Emperor",
    "Oasis Rabbit", 
    "Oasis Sheep",
    "Scarecrow", 
    "Nightmare",
    "Werewolf",
    "Phantom Fisher",
    "Grim Reaper",
    "Frozen Steve",
    "snowman",
    "Grinch", 
    "Yeti",
    "Nutcracker",
    "Reindrake",
    "Nurse Shark",
    "Blue Shark",
    "Tiger Shark",
    "Great White Shark",
    "Magma Slug",
    "Moogma",
    "Lava Leech",
    "Pyroclastic Worm",
    "Fire Eel",
    "Taurus",
    "Lava Flame",
    "Agarimoo",
    "Poisoned Water Worm",
    "Flaming Worm"
]

export let scMessages = {
    'carrot' : 'Is this even a fish? It\'s the Carrot King!',
    'thunder': 'You hear a massive rumble as Thunder emerges${ali}',
    'jawbus' : 'You have angered a legendary creature... Lord Jawbus has arrived${ali}',
    'yeti' : 'What is this creature!?',
    'tiger' : 'A striped beast bounds from the depths, the wild Tiger Shark!',
    'gw' : 'Hide no longer, a Great White Shark has tracked your scent and thirsts for your blood!',
    'fisher' : 'The spirit of a long lost Phantom Fisher has come to haunt you.',
    'reaper' : `This can't be! The manifestation of death himself!`,
    'emp' : 'The Sea Emperor arises from the depths.',
    'nutcracker' : 'You found a forgotten Nutcracker laying beneath the ice.',
    'drake' : 'A Reindrake forms from the depths.',
    'nsquid' : `Pitch Darkness reveals you've caught a Night Squid.`,
    'cow' : `Your Chumcap Bucket trembles, it's an Agarimoo.`,
    'phleg' : `WOAH! A Plhegblast appeared.`,
    'wolf' : 'It must be a full moon, a Werewolf appears.',
    'hydra' : 'The Water Hydra has come to test your strength.',
    'grinch' : `The Grinch stole Jerry's Gifts...get them back!`,
    'miner' : 'A Zombie miner surfaces!'
}

export let nonPingScs = [
    "Squid",
    "Sea Walker",
    "Sea Guardian", 
    "Sea Witch", 
    "Sea Archer", 
    "Rider of the Deep",
    "Catfish",
    "Sea Leech",
    "Guardian Defender",
    "Deep Sea Protector",
    "Oasis Rabbit", 
    "Oasis Sheep",
    "Scarecrow", 
    "Nightmare",
    "Frozen Steve",
    "snowman",
    "Nurse Shark",
    "Blue Shark",
    "Magma Slug",
    "Moogma",
    "Lava Leech",
    "Pyroclastic Worm",
    "Fire Eel",
    "Taurus",
    "Lava Flame",
    "Agarimoo",
    "Poisoned Water Worm",
    "Flaming Worm"
]

export let lsScs = [
    "Carrot King",
    "Thunder",
    "Lord Jawbus",
    "Yeti",
    "Great White Shark",
    "Phantom Fisher",
    "Grim Reaper",
    "Sea Emperor",
    "Sven Packmaster"
]

export let normalLavaScMsgs = [
    "From beneath the lava appears a Magma Slug.",
    "You hear a faint Moo from the lava... A Moogma appears.",
    "A small but fearsome Lava Leech emerges.",
    "You feel the heat radiating as a Pyroclastic Worm surfaces.",
    "A Lava Flame flies out from beneath the lava.",
    "A Fire Eel slithers out from the depths.",
    "Taurus and his Steed Emerge.",
    "WOAH! A Plhlegblast appeared.",
    "You caught a Magma Slug!",
    "You caught a Moogma!",
    "You caught a Lava Leech!",
    "You caught a Pyroclastic Worm!",
    "You caught a Lava Flame!",
    "You caught a Fire Eel!",
    "You caught a Taurus!",
    "You caught a Plhlegblast!"
]